apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    corp.org/author: chipzoller
  name: gooddeployment01
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - image: dummyimagename
        name: container01
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
---
