apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    corp.org/author: chipzoller
  name: product-bravo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prodb
  template:
    metadata:
      labels:
        app: prodb
    spec:
      containers:
      - args:
        - sleep
        - 1d
        image: busybox:1.28
        name: busybox
---
