name: kyverno-policy-test
on:
  - pull_request
  - workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Download Kyverno CLI
        run: |
          curl -sLO https://github.com/kyverno/kyverno/releases/download/v1.7.2/kyverno-cli_v1.7.2_linux_x86_64.tar.gz
          tar -xf kyverno-cli_v1.7.2_linux_x86_64.tar.gz
          ./kyverno version
      - name: Test new resources against existing policies
        run: ./kyverno apply policies/ -r resources/*.yaml
      - name: Test pre-defined cases
        run: ./kyverno test tests/
